// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZMLKyuWERplqBse1OKb7tpvqVu3LKSDk',
    appId: '1:509616406866:web:8d5b977caf28ba4cd9ba8b',
    messagingSenderId: '509616406866',
    projectId: 'site-project-tracker',
    authDomain: 'site-project-tracker.firebaseapp.com',
    storageBucket: 'site-project-tracker.firebasestorage.app',
    measurementId: 'G-TBS7M8C3WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc8169v8QBWGSHGv2NLgBQcjpB_O-_bEQ',
    appId: '1:509616406866:android:fb8698783862fe73d9ba8b',
    messagingSenderId: '509616406866',
    projectId: 'site-project-tracker',
    storageBucket: 'site-project-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTVtFHnXcjhz9OERI4YuX0IBjkFoGIRiM',
    appId: '1:509616406866:ios:17501f4acab82400d9ba8b',
    messagingSenderId: '509616406866',
    projectId: 'site-project-tracker',
    storageBucket: 'site-project-tracker.firebasestorage.app',
    iosClientId: '509616406866-bcjkruu3heb4ll3o53ss3fsdj1tsie9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.siteProjectTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTVtFHnXcjhz9OERI4YuX0IBjkFoGIRiM',
    appId: '1:509616406866:ios:17501f4acab82400d9ba8b',
    messagingSenderId: '509616406866',
    projectId: 'site-project-tracker',
    storageBucket: 'site-project-tracker.firebasestorage.app',
    iosClientId: '509616406866-bcjkruu3heb4ll3o53ss3fsdj1tsie9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.siteProjectTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZMLKyuWERplqBse1OKb7tpvqVu3LKSDk',
    appId: '1:509616406866:web:fe224f9db86c958dd9ba8b',
    messagingSenderId: '509616406866',
    projectId: 'site-project-tracker',
    authDomain: 'site-project-tracker.firebaseapp.com',
    storageBucket: 'site-project-tracker.firebasestorage.app',
    measurementId: 'G-0CDFBRCDG2',
  );
}
